spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/reservation-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/reservation-realm

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8091